UHF-3 Multilingual support
City-of-Helsinki/drupal-helfi pull request #6
Opened 2020-11-04 15:20 UTC by etrml

How to test

- `make new`
- check Drupal UI for 4 languages at `/admin/config/regional/language`
- check that lang negotiation settings are sensible at `admin/config/regional/language/detection`

2020-11-06 08:18 UTC, teroelonen commented
These changes need to be moved to a separate module under the drupal-helfi-platform.

2020-11-10 20:02 UTC, tuutti requested changes

2020-11-10 20:02 UTC, tuutti commented on conf/cmi/migrate_plus.migration.trp_unit.yml
> +uuid: d59ca17f-f697-412b-9ceb-5d16a071a76e
This is leftover from old trp module and should be removed

2020-11-10 20:02 UTC, tuutti commented on public/modules/custom/helfi_editorial/helfi_editorial.module
> +}
Missing newline

2020-11-12 08:47 UTC, tuutti approved these changes

2020-11-12 08:49 UTC, merged